[2024-12-04T08:39:25.709+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-04T08:39:24.363639+00:00 [queued]>
[2024-12-04T08:39:25.723+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-04T08:39:24.363639+00:00 [queued]>
[2024-12-04T08:39:25.724+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-04T08:39:25.740+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_and_extract_kaggle_data> on 2024-12-04 08:39:24.363639+00:00
[2024-12-04T08:39:25.750+0000] {standard_task_runner.py:57} INFO - Started process 1173 to run task
[2024-12-04T08:39:25.755+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_duckdb', 'download_and_extract_kaggle_data', 'manual__2024-12-04T08:39:24.363639+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmp6d698t6b']
[2024-12-04T08:39:25.758+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask download_and_extract_kaggle_data
[2024-12-04T08:39:25.806+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-04T08:39:24.363639+00:00 [running]> on host e919c4bb8fbe
[2024-12-04T08:39:25.884+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_duckdb' AIRFLOW_CTX_TASK_ID='download_and_extract_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T08:39:24.363639+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T08:39:24.363639+00:00'
[2024-12-04T08:39:26.232+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/mannmann2/fortune-500-corporate-headquarters
[2024-12-04T08:39:26.233+0000] {logging_mixin.py:150} INFO - License(s): CC0-1.0
[2024-12-04T08:39:26.793+0000] {logging_mixin.py:150} INFO - Downloading fortune-500-corporate-headquarters.zip to /opt/***
[2024-12-04T08:39:26.798+0000] {logging_mixin.py:150} WARNING -   0%|          | 0.00/37.6k [00:00<?, ?B/s]
[2024-12-04T08:39:26.881+0000] {logging_mixin.py:150} WARNING - 100%|##########| 37.6k/37.6k [00:00<00:00, 473kB/s]
[2024-12-04T08:39:26.882+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 35, in download_and_extract_dataset
    raise FileNotFoundError(f"{zip_name}.zip not found after download.")
FileNotFoundError: fortune-500-HQ.zip not found after download.
[2024-12-04T08:39:26.893+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_to_duckdb, task_id=download_and_extract_kaggle_data, execution_date=20241204T083924, start_date=20241204T083925, end_date=20241204T083926
[2024-12-04T08:39:26.904+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 99 for task download_and_extract_kaggle_data (fortune-500-HQ.zip not found after download.; 1173)
[2024-12-04T08:39:26.932+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-04T08:39:26.954+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
